name: md2pdf

on:
  push:
    branches:    
      - main

jobs:
  job1_md_to_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: mkdir pdfs
      - uses: docker://pandoc/latex
        with:
          args: --pdf-engine=xelatex md/test.md -o pdfs/test.pdf
      - uses: actions/upload-artifact@master
        with:
          name: build
          path: pdfs